In [1]:
import numpy as np
import pandas as pd
import time
import matplotlib.pyplot as plt
import seaborn as sns
import random
from bayes_opt import BayesianOptimization
sns.set()

In [2]:
def get_state(data, t, n):
    d = t - n + 1
    block = data[d : t + 1] if d >= 0 else -d * [data[0]] + data[0 : t + 1]
    res = []
    for i in range(n - 1):
        res.append(block[i + 1] - block[i])
    return np.array([res])

In [3]:
df = pd.read_csv('GNUS.csv')
df.head()

Date   Open   High   Low  Close  Adj Close  Volume
0  2019-02-11  2.280  2.290  2.22   2.22       2.22    9000
1  2019-02-12  2.296  2.296  2.20   2.23       2.23    5200
2  2019-02-13  2.260  2.320  2.12   2.32       2.32   52600
3  2019-02-14  2.203  2.250  2.19   2.20       2.20   38800
4  2019-02-15  2.150  2.150  1.63   2.03       2.03  185700

In [4]:
close = df.Close.values.tolist()
window_size = 30
skip = 5
l = len(close) - 1
close

[2.22,
 2.23,
 2.32,
 2.2,
 2.03,
 2.08,
 2.06,
 2.05,
 2.1,
 2.09,
 2.04,
 2.04,
 2.09,
 2.05,
 2.1,
 2.06,
 2.06,
 1.99,
 2.0]

In [5]:
class Deep_Evolution_Strategy:

    inputs = None

    def __init__(
        self, weights, reward_function, population_size, sigma, learning_rate
    ):
        self.weights = weights
        self.reward_function = reward_function
        self.population_size = population_size
        self.sigma = sigma
        self.learning_rate = learning_rate

    def _get_weight_from_population(self, weights, population):
        weights_population = []
        for index, i in enumerate(population):
            jittered = self.sigma * i
            weights_population.append(weights[index] + jittered)
        return weights_population

    def get_weights(self):
        return self.weights

    def train(self, epoch = 100, print_every = 1):
        lasttime = time.time()
        for i in range(epoch):
            population = []
            rewards = np.zeros(self.population_size)
            for k in range(self.population_size):
                x = []
                for w in self.weights:
                    x.append(np.random.randn(*w.shape))
                population.append(x)
            for k in range(self.population_size):
                weights_population = self._get_weight_from_population(
                    self.weights, population[k]
                )
                rewards[k] = self.reward_function(weights_population)
            rewards = (rewards - np.mean(rewards)) / np.std(rewards)
            for index, w in enumerate(self.weights):
                A = np.array([p[index] for p in population])
                self.weights[index] = (
                    w
                    + self.learning_rate
                    / (self.population_size * self.sigma)
                    * np.dot(A.T, rewards).T
                )
            if (i + 1) % print_every == 0:
                print(
                    'iter %d. reward: %f'
                    % (i + 1, self.reward_function(self.weights))
                )
        print('time taken to train:', time.time() - lasttime, 'seconds')


class Model:
    def __init__(self, input_size, layer_size, output_size):
        self.weights = [
            np.random.randn(input_size, layer_size),
            np.random.randn(layer_size, output_size),
            np.random.randn(layer_size, 1),
            np.random.randn(1, layer_size),
        ]

    def predict(self, inputs):
        feed = np.dot(inputs, self.weights[0]) + self.weights[-1]
        decision = np.dot(feed, self.weights[1])
        buy = np.dot(feed, self.weights[2])
        return decision, buy

    def get_weights(self):
        return self.weights

    def set_weights(self, weights):
        self.weights = weights

In [6]:
class Agent:
    def __init__(
        self,
        population_size,
        sigma,
        learning_rate,
        model,
        money,
        max_buy,
        max_sell,
        skip,
        window_size,
    ):
        self.window_size = window_size
        self.skip = skip
        self.POPULATION_SIZE = population_size
        self.SIGMA = sigma
        self.LEARNING_RATE = learning_rate
        self.model = model
        self.initial_money = money
        self.max_buy = max_buy
        self.max_sell = max_sell
        self.es = Deep_Evolution_Strategy(
            self.model.get_weights(),
            self.get_reward,
            self.POPULATION_SIZE,
            self.SIGMA,
            self.LEARNING_RATE,
        )

    def act(self, sequence):
        decision, buy = self.model.predict(np.array(sequence))
        return np.argmax(decision[0]), int(buy[0])

    def get_reward(self, weights):
        initial_money = self.initial_money
        starting_money = initial_money
        self.model.weights = weights
        state = get_state(close, 0, self.window_size + 1)
        inventory = []
        quantity = 0
        for t in range(0, l, self.skip):
            action, buy = self.act(state)
            next_state = get_state(close, t + 1, self.window_size + 1)
            if action == 1 and initial_money >= close[t]:
                if buy < 0:
                    buy = 1
                if buy > self.max_buy:
                    buy_units = self.max_buy
                else:
                    buy_units = buy
                total_buy = buy_units * close[t]
                initial_money -= total_buy
                inventory.append(total_buy)
                quantity += buy_units
            elif action == 2 and len(inventory) > 0:
                if quantity > self.max_sell:
                    sell_units = self.max_sell
                else:
                    sell_units = quantity
                quantity -= sell_units
                total_sell = sell_units * close[t]
                initial_money += total_sell

            state = next_state
        return ((initial_money - starting_money) / starting_money) * 100

    def fit(self, iterations, checkpoint):
        self.es.train(iterations, print_every = checkpoint)

    def buy(self):
        initial_money = self.initial_money
        state = get_state(close, 0, self.window_size + 1)
        starting_money = initial_money
        states_sell = []
        states_buy = []
        inventory = []
        quantity = 0
        for t in range(0, l, self.skip):
            action, buy = self.act(state)
            next_state = get_state(close, t + 1, self.window_size + 1)
            if action == 1 and initial_money >= close[t]:
                if buy < 0:
                    buy = 1
                if buy > self.max_buy:
                    buy_units = self.max_buy
                else:
                    buy_units = buy
                total_buy = buy_units * close[t]
                initial_money -= total_buy
                inventory.append(total_buy)
                quantity += buy_units
                states_buy.append(t)
                print(
                    'day %d: buy %d units at price %f, total balance %f'
                    % (t, buy_units, total_buy, initial_money)
                )
            elif action == 2 and len(inventory) > 0:
                bought_price = inventory.pop(0)
                if quantity > self.max_sell:
                    sell_units = self.max_sell
                else:
                    sell_units = quantity
                if sell_units < 1:
                    continue
                quantity -= sell_units
                total_sell = sell_units * close[t]
                initial_money += total_sell
                states_sell.append(t)
                try:
                    invest = ((total_sell - bought_price) / bought_price) * 100
                except:
                    invest = 0
                print(
                    'day %d, sell %d units at price %f, investment %f %%, total balance %f,'
                    % (t, sell_units, total_sell, invest, initial_money)
                )
            state = next_state

        invest = ((initial_money - starting_money) / starting_money) * 100
        print(
            '\ntotal gained %f, total investment %f %%'
            % (initial_money - starting_money, invest)
        )
        plt.figure(figsize = (20, 10))
        plt.plot(close, label = 'true close', c = 'g')
        plt.plot(
            close, 'X', label = 'predict buy', markevery = states_buy, c = 'b'
        )
        plt.plot(
            close, 'o', label = 'predict sell', markevery = states_sell, c = 'r'
        )
        plt.legend()
        plt.show()

In [7]:
def best_agent(
    window_size, skip, population_size, sigma, learning_rate, size_network
):
    model = Model(window_size, size_network, 3)
    agent = Agent(
        population_size,
        sigma,
        learning_rate,
        model,
        10000,
        5,
        5,
        skip,
        window_size,
    )
    try:
        agent.fit(10, 1000)
        return agent.es.reward_function(agent.es.weights)
    except:
        return 0

In [8]:
def find_best_agent(
    window_size, skip, population_size, sigma, learning_rate, size_network
):
    global accbest
    param = {
        'window_size': int(np.around(window_size)),
        'skip': int(np.around(skip)),
        'population_size': int(np.around(population_size)),
        'sigma': max(min(sigma, 1), 0.0001),
        'learning_rate': max(min(learning_rate, 0.5), 0.000001),
        'size_network': int(np.around(size_network)),
    }
    print('\nSearch parameters %s' % (param))
    investment = best_agent(**param)
    print('stop after 100 iteration with investment %f' % (investment))
    if investment > accbest:
        costbest = investment
    return investment

In [9]:
accbest = 0.0
NN_BAYESIAN = BayesianOptimization(
    find_best_agent,
    {
        'window_size': (2, 50),
        'skip': (1, 15),
        'population_size': (1, 50),
        'sigma': (0.01, 0.99),
        'learning_rate': (0.000001, 0.49),
        'size_network': (10, 1000),
    },
)
NN_BAYESIAN.maximize(init_points = 30, n_iter = 50, acq = 'ei', xi = 0.0)

|   iter    |  target   | learni... | popula... |   sigma   | size_n... |   skip    | window... |
-------------------------------------------------------------------------------------------------

Search parameters {'window_size': 34, 'skip': 3, 'population_size': 20, 'sigma': 0.6770146704505254, 'learning_rate': 0.3977786862040309, 'size_network': 269}


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide


stop after 100 iteration with investment 0.000000
|  1        |  0.0      |  0.3978   |  19.52    |  0.677    |  268.8    |  3.483    |  34.11    |

Search parameters {'window_size': 10, 'skip': 8, 'population_size': 47, 'sigma': 0.048156567757646575, 'learning_rate': 0.20971744848057539, 'size_network': 737}
stop after 100 iteration with investment 0.000000
|  2        |  0.0      |  0.2097   |  46.69    |  0.04816  |  736.9    |  7.606    |  10.05    |

Search parameters {'window_size': 25, 'skip': 5, 'population_size': 8, 'sigma': 0.44070501970936443, 'learning_rate': 0.4706676215039481, 'size_network': 415}
stop after 100 iteration with investment 0.000000
|  3        |  0.0      |  0.4707   |  7.627    |  0.4407   |  414.9    |  5.04     |  25.28    |

Search parameters {'window_size': 29, 'skip': 11, 'population_size': 13, 'sigma': 0.569966080498838, 'learning_rate': 0.21310072734943442, 'size_network': 933}
stop after 100 iteration with investment 0.000000
|  4        |  0.0    

time taken to train: 0.7583343982696533 seconds
stop after 100 iteration with investment 0.000000
|  23       |  0.0      |  0.405    |  35.53    |  0.975    |  447.8    |  8.483    |  25.74    |

Search parameters {'window_size': 22, 'skip': 14, 'population_size': 1, 'sigma': 0.013296271900300994, 'learning_rate': 0.28379903812729557, 'size_network': 585}
stop after 100 iteration with investment 0.000000
|  24       |  0.0      |  0.2838   |  1.466    |  0.0133   |  584.6    |  14.12    |  22.24    |

Search parameters {'window_size': 6, 'skip': 11, 'population_size': 32, 'sigma': 0.7103186759248623, 'learning_rate': 0.429026065330498, 'size_network': 449}
stop after 100 iteration with investment 0.000000
|  25       |  0.0      |  0.429    |  31.96    |  0.7103   |  449.0    |  10.71    |  5.706    |

Search parameters {'window_size': 19, 'skip': 14, 'population_size': 21, 'sigma': 0.3371780879752772, 'learning_rate': 0.19590605338071174, 'size_network': 456}
stop after 100 iteration

C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 49, 'skip': 14, 'population_size': 49, 'sigma': 0.4235095146816174, 'learning_rate': 0.11276485442331646, 'size_network': 999}
time taken to train: 2.820936441421509 seconds
stop after 100 iteration with investment 0.000000
|  33       |  0.0      |  0.1128   |  49.39    |  0.4235   |  999.1    |  13.89    |  48.95    |

Search parameters {'window_size': 50, 'skip': 5, 'population_size': 49, 'sigma': 0.40256319935744206, 'learning_rate': 0.14831489759216593, 'size_network': 21}
stop after 100 iteration with investment 0.000000
|  34       |  0.0      |  0.1483   |  49.5     |  0.4026   |  20.57    |  4.868    |  49.63    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 50, 'skip': 10, 'population_size': 2, 'sigma': 0.16369112491533538, 'learning_rate': 0.1805509472081788, 'size_network': 996}
stop after 100 iteration with investment 0.000000
|  35       |  0.0      |  0.1806   |  2.076    |  0.1637   |  996.1    |  9.708    |  49.96    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 50, 'skip': 2, 'population_size': 1, 'sigma': 0.8628931180591148, 'learning_rate': 0.04382664163759296, 'size_network': 31}
stop after 100 iteration with investment 0.000000
|  36       |  0.0      |  0.04383  |  1.055    |  0.8629   |  30.56    |  2.416    |  49.89    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 50, 'skip': 14, 'population_size': 48, 'sigma': 0.6260666529462795, 'learning_rate': 0.33871590715707295, 'size_network': 11}
stop after 100 iteration with investment 0.000000
|  37       |  0.0      |  0.3387   |  47.99    |  0.6261   |  11.29    |  13.94    |  49.62    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 2, 'skip': 5, 'population_size': 2, 'sigma': 0.6212223134839031, 'learning_rate': 0.479488804436026, 'size_network': 10}
stop after 100 iteration with investment 0.000000
|  38       |  0.0      |  0.4795   |  1.78     |  0.6212   |  10.48    |  5.057    |  2.091    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 49, 'skip': 14, 'population_size': 1, 'sigma': 0.08582722033742916, 'learning_rate': 0.18237836982083894, 'size_network': 993}
stop after 100 iteration with investment 0.000000
|  39       |  0.0      |  0.1824   |  1.113    |  0.08583  |  993.3    |  13.94    |  49.18    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 49, 'skip': 14, 'population_size': 48, 'sigma': 0.9867609798505947, 'learning_rate': 0.21289584065873668, 'size_network': 984}
time taken to train: 2.914201498031616 seconds
stop after 100 iteration with investment 0.000000
|  40       |  0.0      |  0.2129   |  48.26    |  0.9868   |  984.2    |  13.93    |  49.46    |

Search parameters {'window_size': 50, 'skip': 2, 'population_size': 49, 'sigma': 0.3315338069974025, 'learning_rate': 0.07682471289256713, 'size_network': 21}
stop after 100 iteration with investment 0.000000
|  41       |  0.0      |  0.07682  |  48.98    |  0.3315   |  20.65    |  1.973    |  49.79    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 3, 'skip': 9, 'population_size': 50, 'sigma': 0.12212278705590236, 'learning_rate': 0.35757182768195506, 'size_network': 998}
stop after 100 iteration with investment 0.000000
|  42       |  0.0      |  0.3576   |  49.74    |  0.1221   |  997.9    |  9.052    |  2.523    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 2, 'skip': 14, 'population_size': 49, 'sigma': 0.3567446679394985, 'learning_rate': 0.17184816995203447, 'size_network': 20}
stop after 100 iteration with investment 0.000000
|  43       |  0.0      |  0.1718   |  48.83    |  0.3567   |  19.81    |  14.46    |  2.234    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 2, 'skip': 4, 'population_size': 1, 'sigma': 0.6018457326028593, 'learning_rate': 0.4613120081622245, 'size_network': 11}
stop after 100 iteration with investment 0.000000
|  44       |  0.0      |  0.4613   |  1.004    |  0.6018   |  10.52    |  4.351    |  2.025    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 50, 'skip': 2, 'population_size': 3, 'sigma': 0.889528930253569, 'learning_rate': 0.44909514002762585, 'size_network': 991}
stop after 100 iteration with investment 0.000000
|  45       |  0.0      |  0.4491   |  2.702    |  0.8895   |  991.5    |  1.996    |  49.79    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 50, 'skip': 15, 'population_size': 3, 'sigma': 0.29565433966918087, 'learning_rate': 0.35076488263622974, 'size_network': 20}
stop after 100 iteration with investment 0.000000
|  46       |  0.0      |  0.3508   |  3.084    |  0.2957   |  19.52    |  14.7     |  49.84    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 49, 'skip': 12, 'population_size': 50, 'sigma': 0.8362829726387121, 'learning_rate': 0.4187626807481458, 'size_network': 22}
stop after 100 iteration with investment 0.000000
|  47       |  0.0      |  0.4188   |  49.52    |  0.8363   |  21.8     |  12.22    |  49.13    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 50, 'skip': 2, 'population_size': 50, 'sigma': 0.08938258631268399, 'learning_rate': 0.018218797478264596, 'size_network': 997}


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide


stop after 100 iteration with investment 0.000000
|  48       |  0.0      |  0.01822  |  49.73    |  0.08938  |  996.9    |  1.944    |  49.63    |

Search parameters {'window_size': 2, 'skip': 14, 'population_size': 48, 'sigma': 0.6523154131600233, 'learning_rate': 0.47553245738243144, 'size_network': 986}
stop after 100 iteration with investment 0.000000
|  49       |  0.0      |  0.4755   |  48.34    |  0.6523   |  986.5    |  14.08    |  2.03     |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 50, 'skip': 15, 'population_size': 2, 'sigma': 0.7816087332067627, 'learning_rate': 0.4564111057382225, 'size_network': 999}
stop after 100 iteration with investment 0.000000
|  50       |  0.0      |  0.4564   |  2.369    |  0.7816   |  999.0    |  14.54    |  49.78    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 3, 'skip': 2, 'population_size': 1, 'sigma': 0.5837813805306361, 'learning_rate': 0.24647959716160692, 'size_network': 976}
stop after 100 iteration with investment 0.000000
|  51       |  0.0      |  0.2465   |  1.226    |  0.5838   |  975.8    |  1.975    |  3.187    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 2, 'skip': 13, 'population_size': 2, 'sigma': 0.8091248635694761, 'learning_rate': 0.43983775644770645, 'size_network': 26}
stop after 100 iteration with investment 0.000000
|  52       |  0.0      |  0.4398   |  2.174    |  0.8091   |  25.52    |  12.91    |  2.006    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 2, 'skip': 4, 'population_size': 49, 'sigma': 0.93667549881947, 'learning_rate': 0.17312025585106003, 'size_network': 10}
time taken to train: 0.10254549980163574 seconds
stop after 100 iteration with investment 0.000000
|  53       |  0.0      |  0.1731   |  49.46    |  0.9367   |  10.37    |  3.533    |  2.042    |

Search parameters {'window_size': 3, 'skip': 14, 'population_size': 49, 'sigma': 0.6498262956538561, 'learning_rate': 0.20614032430444357, 'size_network': 998}
time taken to train: 0.49904632568359375 seconds
stop after 100 iteration with investment 0.000000
|  54       |  0.0      |  0.2061   |  48.98    |  0.6498   |  998.2    |  14.35    |  3.39     |

Search parameters {'window_size': 50, 'skip': 13, 'population_size': 2, 'sigma': 0.6921115893878222, 'learning_rate': 0.44672303794560336, 'size_network': 18}
stop after 100 iteration with investment 0.000000
|  55       |  0.0      |  0.4467   |  1.574    |  0.6921   |  18.42    |  13.

C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 3, 'skip': 2, 'population_size': 1, 'sigma': 0.39966022851543387, 'learning_rate': 0.3230654842674296, 'size_network': 992}
stop after 100 iteration with investment 0.000000
|  56       |  0.0      |  0.3231   |  1.499    |  0.3997   |  992.1    |  2.213    |  2.994    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 50, 'skip': 2, 'population_size': 50, 'sigma': 0.25434703549956167, 'learning_rate': 0.4150439423294323, 'size_network': 990}


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide


stop after 100 iteration with investment 0.000000
|  57       |  0.0      |  0.415    |  49.64    |  0.2543   |  989.7    |  2.419    |  49.84    |

Search parameters {'window_size': 49, 'skip': 1, 'population_size': 49, 'sigma': 0.7376218178538204, 'learning_rate': 0.2040191265157932, 'size_network': 25}
stop after 100 iteration with investment 0.000000
|  58       |  0.0      |  0.204    |  49.48    |  0.7376   |  25.24    |  1.226    |  48.92    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 2, 'skip': 1, 'population_size': 50, 'sigma': 0.652451342996919, 'learning_rate': 0.1912952575940007, 'size_network': 25}
time taken to train: 0.2666151523590088 seconds
stop after 100 iteration with investment 0.000000
|  59       |  0.0      |  0.1913   |  49.67    |  0.6525   |  25.01    |  1.094    |  2.199    |

Search parameters {'window_size': 2, 'skip': 1, 'population_size': 2, 'sigma': 0.5091945238470109, 'learning_rate': 0.07932797891612826, 'size_network': 1000}
stop after 100 iteration with investment 0.000000
|  60       |  0.0      |  0.07933  |  1.869    |  0.5092   |  999.9    |  1.201    |  2.123    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 50, 'skip': 2, 'population_size': 2, 'sigma': 0.01090654906378083, 'learning_rate': 0.09760102608864617, 'size_network': 35}
stop after 100 iteration with investment 0.000000
|  61       |  0.0      |  0.0976   |  2.133    |  0.01091  |  35.19    |  1.586    |  49.62    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 49, 'skip': 14, 'population_size': 1, 'sigma': 0.4763289915098312, 'learning_rate': 0.1676993802007788, 'size_network': 990}
stop after 100 iteration with investment 0.000000
|  62       |  0.0      |  0.1677   |  1.348    |  0.4763   |  990.4    |  14.25    |  49.23    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 3, 'skip': 14, 'population_size': 2, 'sigma': 0.8026460913077111, 'learning_rate': 0.02749221510851976, 'size_network': 32}
stop after 100 iteration with investment 0.000000
|  63       |  0.0      |  0.02749  |  1.742    |  0.8026   |  32.17    |  14.03    |  2.629    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 3, 'skip': 15, 'population_size': 49, 'sigma': 0.16459840549103574, 'learning_rate': 0.08157014175459211, 'size_network': 997}


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide


stop after 100 iteration with investment 0.000000
|  64       |  0.0      |  0.08157  |  49.05    |  0.1646   |  997.3    |  14.68    |  2.557    |

Search parameters {'window_size': 2, 'skip': 14, 'population_size': 49, 'sigma': 0.4830777856750286, 'learning_rate': 0.18141659606640229, 'size_network': 18}
stop after 100 iteration with investment 0.000000
|  65       |  0.0      |  0.1814   |  48.82    |  0.4831   |  17.53    |  14.29    |  2.224    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 49, 'skip': 1, 'population_size': 50, 'sigma': 0.12770703059914987, 'learning_rate': 0.002984318600105581, 'size_network': 15}
stop after 100 iteration with investment 0.000000
|  66       |  0.0      |  0.002984 |  49.76    |  0.1277   |  14.56    |  1.26     |  49.27    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 47, 'skip': 14, 'population_size': 50, 'sigma': 0.8453861524370384, 'learning_rate': 0.07197886803169203, 'size_network': 1000}
time taken to train: 2.900033950805664 seconds
stop after 100 iteration with investment 0.000000
|  67       |  0.0      |  0.07198  |  49.99    |  0.8454   |  999.7    |  14.02    |  47.3     |

Search parameters {'window_size': 49, 'skip': 15, 'population_size': 2, 'sigma': 0.12616987758043324, 'learning_rate': 0.31311838635833533, 'size_network': 991}
stop after 100 iteration with investment 0.000000
|  68       |  0.0      |  0.3131   |  2.298    |  0.1262   |  990.9    |  15.0     |  48.98    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 3, 'skip': 1, 'population_size': 2, 'sigma': 0.8192565065414829, 'learning_rate': 0.2884024720213759, 'size_network': 21}
stop after 100 iteration with investment 0.000000
|  69       |  0.0      |  0.2884   |  2.129    |  0.8193   |  21.24    |  1.116    |  3.109    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 50, 'skip': 14, 'population_size': 2, 'sigma': 0.7185025168045761, 'learning_rate': 0.47997787341712644, 'size_network': 11}
stop after 100 iteration with investment 0.000000
|  70       |  0.0      |  0.48     |  1.836    |  0.7185   |  11.34    |  13.77    |  49.57    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 49, 'skip': 15, 'population_size': 1, 'sigma': 0.5717408258925939, 'learning_rate': 0.3592759193750641, 'size_network': 36}
stop after 100 iteration with investment 0.000000
|  71       |  0.0      |  0.3593   |  1.338    |  0.5717   |  35.88    |  14.56    |  49.07    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 3, 'skip': 14, 'population_size': 3, 'sigma': 0.27194368349518894, 'learning_rate': 0.3361392363991618, 'size_network': 987}
stop after 100 iteration with investment 0.000000
|  72       |  0.0      |  0.3361   |  2.721    |  0.2719   |  987.0    |  13.96    |  2.809    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 3, 'skip': 14, 'population_size': 49, 'sigma': 0.4881438863840456, 'learning_rate': 0.3066998642393742, 'size_network': 22}
stop after 100 iteration with investment 0.000000
|  73       |  0.0      |  0.3067   |  48.72    |  0.4881   |  22.46    |  13.98    |  2.896    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 49, 'skip': 3, 'population_size': 49, 'sigma': 0.01978174272608589, 'learning_rate': 0.47313600286609386, 'size_network': 972}


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide


stop after 100 iteration with investment 0.000000
|  74       |  0.0      |  0.4731   |  49.08    |  0.01978  |  972.2    |  2.728    |  48.76    |

Search parameters {'window_size': 48, 'skip': 14, 'population_size': 50, 'sigma': 0.010211593211481464, 'learning_rate': 0.30581014192782047, 'size_network': 12}
stop after 100 iteration with investment 0.000000
|  75       |  0.0      |  0.3058   |  49.68    |  0.01021  |  12.29    |  14.49    |  47.63    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 4, 'skip': 14, 'population_size': 50, 'sigma': 0.5296885183697544, 'learning_rate': 0.46280918974022145, 'size_network': 996}


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide


stop after 100 iteration with investment 0.000000
|  76       |  0.0      |  0.4628   |  49.51    |  0.5297   |  996.0    |  14.43    |  3.985    |

Search parameters {'window_size': 49, 'skip': 2, 'population_size': 1, 'sigma': 0.06238772261710794, 'learning_rate': 0.4891504918923353, 'size_network': 999}
stop after 100 iteration with investment 0.000000
|  77       |  0.0      |  0.4892   |  1.426    |  0.06239  |  999.4    |  1.639    |  49.16    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 3, 'skip': 1, 'population_size': 50, 'sigma': 0.3695112146343926, 'learning_rate': 0.29398959106991035, 'size_network': 972}
stop after 100 iteration with investment 0.000000
|  78       |  0.0      |  0.294    |  49.54    |  0.3695   |  972.3    |  1.436    |  3.018    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 2, 'skip': 1, 'population_size': 4, 'sigma': 0.46171298495463864, 'learning_rate': 0.315888124889866, 'size_network': 31}
stop after 100 iteration with investment 0.000000
|  79       |  0.0      |  0.3159   |  4.401    |  0.4617   |  31.19    |  1.217    |  2.392    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide



Search parameters {'window_size': 49, 'skip': 15, 'population_size': 47, 'sigma': 0.4729894682805449, 'learning_rate': 0.2592588915902506, 'size_network': 25}
stop after 100 iteration with investment 0.000000
|  80       |  0.0      |  0.2593   |  47.06    |  0.473    |  24.54    |  14.75    |  49.47    |


C:\Users\Kyle\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: RuntimeWarning: invalid value encountered in true_divide


In [11]:
print('Best AGENT accuracy value: %f' % NN_BAYESIAN.res['max']['max_val'])
print('Best AGENT parameters: ', NN_BAYESIAN.res['max']['max_params'])

TypeError: list indices must be integers or slices, not str

In [14]:
# this is my parameter
best_agent(30, 1, 15, 0.1, 0.03, 500)

time taken to train: 8.902231216430664 seconds


44.664403540000016

In [32]:
# this is from bayesian
best_agent(20, 1, 34, 0.7152490670931403, 0.28208006704411104, 176)

[[ -8.08350637 -34.28026983  -2.66784998]] [[-8.85968201]]
[[-21.42116526 -43.36871289 -12.98324049]] [[-5.27531589]]
[[-31.20257693 -45.73055655 -68.41548793]] [[-21.51502866]]
[[ -26.54570657    1.33010818 -168.56409898]] [[-102.46715733]]
[[ -31.06672918   82.78805877 -118.08289735]] [[-196.65620346]]
[[-360.04687086 -187.98393899  135.59540435]] [[55.14417243]]
[[ 216.06513331 -122.13677575  119.63899647]] [[150.48276225]]
[[   7.14853009  -92.13262333 -406.71426577]] [[74.40116283]]
[[  66.77509856  229.2818813  -358.59636441]] [[-369.44265858]]
[[-600.97350028 -108.32056746   58.56259128]] [[-123.93845594]]
[[-170.00830939 -209.24221528  432.56182275]] [[375.15145919]]
[[ 694.40112285 -344.58423664   84.58451989]] [[224.19035294]]
[[-523.94736014 -218.45031875  206.10602357]] [[566.83308402]]
[[ 376.95589231 -356.21165995  158.36921279]] [[71.32343046]]
[[  637.63181439   984.4030414  -1272.6804366 ]] [[-495.40771381]]
[[-1627.69514607   -67.40342874  -908.40170067]] [[-1213.6005

[[ 5.2403886   5.84244791 18.69444227]] [[-12.94196862]]
[[-43.88864637  11.08161132   8.41770921]] [[-19.5019908]]
[[-153.77231734   19.44659911  -51.2847492 ]] [[-61.83650613]]
[[-189.05967619   15.2976115  -171.61640499]] [[-152.09001023]]
[[ 139.7857799    -1.53611605 -200.15471167]] [[-180.07637911]]
[[-266.61113612  139.66128576  -86.43846877]] [[-67.84941589]]
[[ 175.42710317  146.42885246 -170.95010662]] [[-107.25926068]]
[[-402.82973084  101.64185246 -318.649675  ]] [[-234.6531114]]
[[ 189.82677329   -3.02368898 -323.13187942]] [[-327.42442417]]
[[ -52.23570879  142.39910086 -289.61685979]] [[-146.95895063]]
[[101.54534008 233.42497943 -58.40160701]] [[252.1044666]]
[[1256.96710295 -203.71170777   -4.20125647]] [[-263.10716954]]
[[-87.69477182 124.71115286 857.17261303]] [[480.51843831]]
[[-422.47460944  255.56758726  271.71003175]] [[101.74435171]]
[[  94.12592925 -320.03976167 -489.21201313]] [[-52.61635047]]
[[-2233.0125435   -865.12685381  -400.23954672]] [[-640.29116358]]

[[-1.98894647 30.42135038 -0.72367398]] [[-22.70645087]]
[[-25.93093438  77.53756869  -7.34410359]] [[-66.23781306]]
[[-14.70273348 102.41049577   6.07309312]] [[-80.07725325]]
[[ 61.21763011 -11.21493851  40.04428829]] [[43.07826315]]
[[-276.4385812   163.82039698 -149.69967218]] [[-171.59824432]]
[[228.84328022 126.49901641   2.97567539]] [[-41.94098559]]
[[-153.02089574  240.42730646 -218.12501664]] [[-227.8853882]]
[[ -42.58054583 -116.31092662   -0.77720472]] [[266.11822889]]
[[-214.47548091  219.078466    -60.49324931]] [[9.30352913]]
[[   2.35985106  161.37231122 -204.36101859]] [[194.1458411]]
[[ 920.90590726 -576.51597333  111.61673961]] [[219.53689891]]
[[-1134.22870196  -361.20943526  -630.00644036]] [[277.04314992]]
[[157.5889717  515.40539567 253.68499881]] [[-442.4971078]]
[[712.36812623 410.92502849 406.4123957 ]] [[588.36273692]]
[[-1193.99076678  -458.07427989  -126.85687647]] [[46.29349811]]
[[-237.8246461   -93.03158481  605.10492727]] [[-297.41570993]]
[[ 688.026391

[[  3.34777963 -73.86024992 -19.67692444]] [[-70.91343579]]
[[-236.63207733  119.63945203   73.83108237]] [[29.89703884]]
[[ 66.81637303 337.4565123   73.99054436]] [[-206.39107413]]
[[ -91.06769415  391.36737084 -370.32451602]] [[-189.38040583]]
[[ 243.72132102   11.8799083  -412.68240882]] [[-219.11296807]]
[[-140.86358449  -63.20799519  253.83239501]] [[366.50624088]]
[[-138.40728567  293.58332177  177.02535412]] [[-83.01179768]]
[[ 247.88889059 -247.23576015   83.44605378]] [[-357.52825607]]
[[-232.10817513 -113.39320038 -276.84870795]] [[32.81809712]]
[[ 731.95849005  674.80649294 -146.74630409]] [[159.1665999]]
[[ 487.60745407 -178.51668268 -741.25959764]] [[196.15668181]]
[[ -806.13743049 -1211.618945   -1495.22334808]] [[83.35011965]]
[[-309.18230545   -8.21736107  473.65748727]] [[-65.90703863]]
[[-627.24932834  948.39235206  847.81226754]] [[-782.19548623]]
[[ 4.47874886 -5.3139823  -2.72865244]] [[-4.26561059]]
[[-17.10691657 -14.41054886  -5.69600797]] [[-4.2350413]]
[[-62.

[[ 89.57821277 141.9836     -96.48631998]] [[-90.36769612]]
[[ 193.90913175  244.8552213  -198.37141169]] [[-158.62077235]]
[[  51.11393151   22.09188844 -141.02172586]] [[-80.2760503]]
[[-372.87984239   81.38503437  -36.74715845]] [[-83.37532788]]
[[150.90391874 199.17559005  45.74824604]] [[-41.327573]]
[[ 396.53311407  391.81675111 -368.00299929]] [[-90.55987195]]
[[ 398.98635936  152.55410596 -412.26074641]] [[-224.35242707]]
[[-479.26318691  -55.88498326  -90.8094173 ]] [[135.0734032]]
[[-452.23723846  -87.87957374  271.93773072]] [[92.00866054]]
[[ 109.52387299 -744.24075083  320.16469319]] [[551.46492693]]
[[-751.65915404 -879.86065635  240.65076665]] [[244.01561791]]
[[695.69797063 702.7593048   21.06384023]] [[-142.73705238]]
[[1979.0675106   758.64883189 -540.1073052 ]] [[100.81414536]]
[[ -283.48044731    24.54360306 -1439.81109815]] [[-778.24374346]]
[[-653.63911182  876.05591442  -74.06840883]] [[-1180.32813075]]
[[-298.29694417  338.78820699   41.33837684]] [[-181.9042377

[[ -204.52638015   100.98881075 -1166.23689237]] [[-78.18510467]]
[[-237.05396514 -315.81461557 -260.88403775]] [[-571.32399242]]
[[-1069.77728374  -960.713035     993.18383844]] [[-996.05774768]]
[[263.50910619 462.35840657 117.97838598]] [[-1846.79562618]]
[[13.74668082 -8.48828443 13.52364688]] [[-12.67904523]]
[[ 22.89643611 -16.3804456   31.03416006]] [[-47.27312394]]
[[ 37.31887149 -30.54632106  37.51154743]] [[-159.5467982]]
[[ 18.92661268 -21.09725824 -63.27994181]] [[-286.94456681]]
[[ -75.16945743   43.26633528 -295.86567185]] [[-135.87410871]]
[[ 57.58179848 -85.86398223  76.39269887]] [[-225.92601802]]
[[ 83.47094439 -99.40931878 -24.64475517]] [[-103.54472544]]
[[ 249.13259973 -103.07443367   58.05409771]] [[-493.81373939]]
[[   4.66757431  153.85149671 -600.68517787]] [[-265.94199095]]
[[211.54240642 -76.19316875  43.05689769]] [[-377.26030711]]
[[ -78.36683307 -126.68185198   98.46536489]] [[73.17757335]]
[[ 153.47938205 -206.29145848  -81.2771593 ]] [[754.147198]]
[[ 91

[[-159.16621798 -347.68201949  550.37983668]] [[487.71413577]]
[[   7.55106366   28.86011867 -397.71698527]] [[-685.17275326]]
[[  69.21652901  765.03380048 -966.12080547]] [[-385.17759356]]
[[-1351.93398819   262.30237877 -1282.07739598]] [[-1436.44058374]]
[[-611.35732647 -344.83702447 -324.33656535]] [[-257.34604383]]
[[726.48397969 390.34004513 -97.04804571]] [[-904.43034475]]
[[-4.93959242 -2.62622433 -9.58232467]] [[16.31543085]]
[[ -4.56502745   8.56236431 -17.2431885 ]] [[6.44444214]]
[[ -2.7373855   30.38143619 -40.4938153 ]] [[-35.80027483]]
[[-12.06307259  40.70707539 -51.17185539]] [[-106.42047058]]
[[-53.42977408 -13.21221167  14.20289199]] [[-84.93052053]]
[[-62.41897205 135.84592857 -36.6554327 ]] [[-1.89521693]]
[[  92.69335118   12.46557677 -215.39351789]] [[62.86129759]]
[[ 111.50580103  272.59881887 -329.85735415]] [[-202.86190341]]
[[-141.55764636 -155.11978816 -119.95120119]] [[-299.55130414]]
[[ 17.71591957 120.27752984 303.45288536]] [[-8.65366553]]
[[ -91.384669

[[321.50553312 285.83838475 187.17940297]] [[303.44210704]]
[[ 620.05601186 -246.75656606   66.8618941 ]] [[673.23257492]]
[[-529.15269489 -881.9178945   -27.95158362]] [[-143.80030981]]
[[845.09949872  43.17005981 -78.20517852]] [[-1242.95847893]]
[[ -28.26347863  318.39922121 -285.68131853]] [[168.11705427]]
[[-1243.83844198  -368.37160101  -225.84034225]] [[-54.70337758]]
[[  -9.64750493  411.18868139 -172.89102934]] [[-656.60065105]]
[[ 679.51391177 1143.77560431 -339.89003004]] [[-84.65500119]]
[[-26.58884228 -21.88315487  -3.49643573]] [[-13.16989277]]
[[-10.09034201 -35.09531684 -23.91203181]] [[-19.63245525]]
[[ 22.29302987 -78.7675096  -86.71726399]] [[-52.29529647]]
[[  -2.90609482 -104.06547197 -152.39573974]] [[-110.00584985]]
[[-189.31455892    8.2405943   -33.47962372]] [[-88.06061351]]
[[ -3.83610964  -6.3800961  -39.6505914 ]] [[1.80834974]]
[[ 153.55338322 -134.19486112   57.10326479]] [[-56.47849241]]
[[ 326.12272531  -33.20061593 -431.79929698]] [[-305.63666268]]
[[-

[[158.06965982 419.81445053 -14.03392874]] [[-102.22436594]]
[[ 15.31436082 317.46304003 149.18066825]] [[-111.57413349]]
[[ 396.23331273  146.257922   -363.51182445]] [[-237.41441838]]
[[-39.19984209 -13.60042624  96.65010329]] [[53.56903167]]
[[-252.85400199  525.29765156  277.76475168]] [[75.70223935]]
[[  769.01330224  -241.45147314 -1077.98872378]] [[-58.05798411]]
[[-910.10726372 -736.55237438  148.40824292]] [[483.16511496]]
[[-86.97180983 216.12952315 601.80173667]] [[-152.97134009]]
[[1237.50781191  501.52897965 -859.25495223]] [[-839.53824478]]
[[-791.23558237 -644.04220891  669.56142861]] [[47.23892966]]
[[166.94058155 956.57906757 338.49981322]] [[-740.20645205]]
[[ 494.89267433 1602.68819771   46.41819513]] [[-319.72363553]]
[[ 15.30220081 -29.93528591  -3.73015092]] [[-10.82114946]]
[[ 29.75815905  -6.77896973 -18.76181882]] [[-20.81380218]]
[[ 82.48819319 103.6654379  -93.51995142]] [[-70.03122103]]
[[ 113.46864464  252.5033141  -198.61406621]] [[-158.70218557]]
[[ -70.8

[[111.32892336 103.44118135  -5.66168993]] [[-49.48668943]]
[[ 128.86553242  128.16668458 -101.82849687]] [[-105.35359763]]
[[-117.36449609  -76.19487423 -194.7782347 ]] [[-98.05756938]]
[[-220.1367371   -39.10639906  223.46819365]] [[-81.69783601]]
[[ 363.00572223  361.56622205 -191.32981395]] [[-13.15872303]]
[[ 298.49147897  412.86330507 -317.05234012]] [[-185.63921819]]
[[-137.08344385  -51.62978073 -403.84807859]] [[-108.8112935]]
[[-497.031947   -338.19162023  371.57217881]] [[-228.4291337]]
[[102.64155926 175.56426287   0.93501238]] [[364.95480802]]
[[ 231.19147898   31.59694927 -942.3060685 ]] [[91.89626154]]
[[-522.60355648 -281.34416523  662.83288053]] [[175.82296333]]
[[1005.78308334  635.24113112  738.20777042]] [[-219.8876048]]
[[ 1379.55551396   560.22205411 -1121.50670232]] [[144.19164551]]
[[-1465.8647581  -1261.78229539  -104.01915101]] [[114.53140463]]
[[-339.82259318 -596.12488004 1094.93718838]] [[-887.62097756]]
[[ 652.23798445  627.20723782 -584.06318439]] [[-638.

[[ 91.45854196 103.29792847 -25.14819246]] [[-200.41908861]]
[[142.31536957 -29.1493118  -63.58863853]] [[-15.51522501]]
[[-139.47095227  232.25942679  105.53989629]] [[101.16277617]]
[[ 166.62042631   78.3876639  -162.20448434]] [[80.98169067]]
[[ 184.92044334  268.4980214  -251.94098911]] [[-587.26553438]]
[[ 309.03507618 -130.48735361  -77.35036329]] [[-195.54962332]]
[[154.76350277 -96.53849467 196.39630117]] [[126.39750515]]
[[-155.25275283  144.821788     73.91066287]] [[617.11421254]]
[[ 666.16665467 -463.88997854 -744.37888571]] [[301.89790536]]
[[-489.81930868   28.93680814  191.5506895 ]] [[155.58803956]]
[[520.66787255 -12.85705605 319.34101435]] [[-532.67575564]]
[[ 909.65066287 -581.83003266 -357.82398564]] [[-1182.96306471]]
[[-530.81338048  437.52825909  808.96599584]] [[-745.28817518]]
[[117.00712671 152.87725349 340.73774587]] [[407.08168321]]
[[ 469.4434061   897.22115895 -994.93510937]] [[-178.57065393]]
[[ 13.81105638 -12.50927454  -5.00070431]] [[-17.64220858]]
[[ 

[[16.03906046  4.29211814 34.56868866]] [[14.50707746]]
[[63.46039241 -7.62564581 36.06271538]] [[50.72627684]]
[[70.14641476 49.79781252  7.28686795]] [[7.40854859]]
[[-127.42296245  166.54120597  -63.64555281]] [[-214.71750818]]
[[-132.33510026 -211.50157392  -12.06533629]] [[52.50764083]]
[[ 163.86141298   71.66879456 -195.7244126 ]] [[182.15809019]]
[[ 161.13088336  261.7997577  -173.46546106]] [[229.78444693]]
[[-219.92196842  302.91980067  -33.73122304]] [[-211.4038942]]
[[-219.98363641 -153.98956957   95.50769707]] [[-200.81012467]]
[[-235.95840897 -205.86759028   67.05301476]] [[365.90197328]]
[[  43.65368972  742.99147321 -721.2546866 ]] [[-104.55143878]]
[[-637.53566365  -76.05815186  101.37199616]] [[354.17855107]]
[[ 947.70507912 -666.76504843  444.21333926]] [[647.70282107]]
[[ 444.18483554 1310.48606795  707.3866316 ]] [[-278.55797888]]
[[-824.0674596  -621.46872367 1021.48826332]] [[-399.54420184]]
[[  140.30887149 -1357.80918506  -221.38655687]] [[-388.54008493]]
[[  21

[[ 786.79746519  -69.13299731 -767.8831709 ]] [[-1364.160533]]
[[10.88817902 -5.07927622 -8.58749017]] [[-15.37807065]]
[[  7.29981146 -15.18325711  -4.5092978 ]] [[-13.66913796]]
[[ 19.25330189 -12.52148271  -9.75173282]] [[-3.81260216]]
[[ 61.04198353  29.49222184 -33.13277337]] [[-6.21928298]]
[[57.35224643 70.57448054 -9.06510435]] [[-69.13937859]]
[[-204.43852214 -251.48503561  234.29395249]] [[-145.31923138]]
[[-52.24226189 118.99180196   1.90536259]] [[12.01234515]]
[[ -17.47885983   40.37447836 -271.94910934]] [[-15.08102708]]
[[ -48.10967708  368.63664033 -141.76904805]] [[42.54998413]]
[[  37.50287889 -226.2268249   353.93246764]] [[-112.74473393]]
[[-395.56024381 -386.01798832  200.59234683]] [[175.20297051]]
[[-109.88627198  240.93592139 -524.78491685]] [[-100.85873456]]
[[-942.27098314 -461.60262763 -152.11836974]] [[-231.88140134]]
[[153.27218733 550.08953371 351.52305719]] [[253.18275789]]
[[ 1412.13133162   433.40937313 -1157.64521356]] [[929.10262096]]
[[ -346.38149033

[[1065.15135902 -382.12022734 -265.35499931]] [[292.91732259]]
[[-1150.1471893   -299.79412985  -125.62171766]] [[-578.84113252]]
[[ -551.42282549 -1023.04104814    26.51982015]] [[-1500.34009719]]
[[1310.64498252 -463.27109257 -724.74572861]] [[683.37041687]]
[[ -9.76016155 -17.92861334  -8.74943788]] [[5.0652268]]
[[-29.38411713 -17.74295704 -14.42963557]] [[3.1395983]]
[[-85.66120546 -18.01576363 -44.20515417]] [[-20.77801642]]
[[-133.65119864  -35.66379951  -67.68140482]] [[-55.95853854]]
[[-31.16315209 -92.61581291  49.22877454]] [[-27.31749084]]
[[-118.12357747 -139.89118273  221.30585539]] [[117.58793839]]
[[  5.11423834 -44.30189171 -73.24217255]] [[-93.56343076]]
[[-161.06821428  -28.77899956 -316.48434629]] [[42.75941231]]
[[-200.78937277  -85.03352837   16.431182  ]] [[-254.78914535]]
[[ -20.78483424 -260.59422711  583.86101323]] [[271.80603357]]
[[ -36.81846388 -376.46845576  316.66648152]] [[126.01112233]]
[[ 695.28345335  -98.12107802 -408.92683694]] [[21.19310646]]
[[-49

[[  24.51979857  503.65091286 -295.28569352]] [[-1325.38056562]]
[[ 11.38274077 -27.69492396   6.37403237]] [[6.95616796]]
[[  5.42776256 -26.07443418  31.97888118]] [[7.3816363]]
[[-15.59683259 -10.15880643  79.38398668]] [[-36.40995607]]
[[-47.00896608  26.62247262  55.30911014]] [[-133.57722986]]
[[ -66.99159907   43.96330408 -133.27655116]] [[-126.68877811]]
[[-96.53556969 -14.30287635 228.17246443]] [[272.56814725]]
[[64.87528852 57.46362306 78.25588   ]] [[-116.27224015]]
[[249.09008058  76.7172298  -56.49570155]] [[-43.96234296]]
[[-398.0378693    56.71736414 -211.12820847]] [[-381.63096452]]
[[ -97.77928832 -296.54061822    8.62426287]] [[522.96311505]]
[[-306.17132647  124.67996041  368.95159495]] [[234.99922899]]
[[1021.40805981 -112.32110269 -783.83352189]] [[-4.51520381]]
[[ 138.94242393 -190.93390467 -192.94786842]] [[527.69625048]]
[[-187.65143778 -631.81700378  694.28774782]] [[231.33619631]]
[[ -63.33464472  150.04471614 -754.7309835 ]] [[-1188.02046304]]
[[-1073.918188

[[ -25.55466456 -468.45593991 -198.60846971]] [[-290.94592994]]
[[-351.98261063  -90.99086174  138.39924591]] [[16.53830582]]
[[-384.94533319  130.88683339  450.73539268]] [[384.82338554]]
[[536.11707497  69.8547489  392.79022561]] [[-12.12570144]]
[[-931.47877095  -83.10170637 -239.72596833]] [[-77.23831272]]
[[ 552.13460178   76.21218913 -455.99647388]] [[823.09460692]]
[[ 761.78357023 -629.4035041  -791.40251636]] [[-200.21524989]]
[[-873.36760634 -563.55292617 -183.31421339]] [[-1290.73421135]]
[[-862.52651697 -257.36364779  922.57924715]] [[256.49554469]]
[[ 525.77767352 1082.59759171  467.29294115]] [[-135.51657373]]
[[ -0.31528226 -10.87164703   0.77788843]] [[-8.42259971]]
[[  8.91870387 -18.26303312  17.86022807]] [[-27.3362156]]
[[33.12528619 -5.76169762 37.99369045]] [[-56.36247715]]
[[-14.03232526  39.71573395 -22.21062841]] [[-29.68414847]]
[[-244.12455403   57.19858012 -196.71865992]] [[132.5528697]]
[[-234.91719715 -258.33350796  147.02846982]] [[-120.49883758]]
[[287.11

[[  767.49648683   548.6474631  -1063.3384273 ]] [[-13.63343426]]
[[ 132.20209606 -174.70139758 -608.71775053]] [[-265.13139673]]
[[-831.28061827 -276.77726598 1107.24448967]] [[210.90602105]]
[[-223.42467308   78.2057137  -555.46344644]] [[-966.90914642]]
[[ 2.93675599 -9.25008133 -6.33269589]] [[8.10515632]]
[[ 40.6205878  -24.15167319  -6.12098977]] [[13.24756518]]
[[150.04883634 -53.47052559   2.9393817 ]] [[3.77560164]]
[[183.35792618 -59.87378062   3.07165618]] [[-91.71697608]]
[[-214.59465704   11.42693549  -38.32606449]] [[-248.91699779]]
[[-133.76580342 -191.374437   -112.01429772]] [[-65.49871375]]
[[293.53100655 -11.73641114 120.062927  ]] [[103.0029318]]
[[ 594.61987658 -143.66080406  -20.48269849]] [[-184.00553423]]
[[-302.51796655  -98.98451799  214.85429677]] [[-158.43949799]]
[[-403.3607243  -205.16832705 -323.39750476]] [[-423.73207272]]
[[-291.202444   -248.14927485   63.95109781]] [[214.33393105]]
[[ -89.66451167   35.65988374 -105.31435229]] [[-312.47502029]]
[[-743

[[-123.77783695  145.62067698 -598.67630445]] [[-460.43527143]]
[[-258.18403302  -58.17639362 -282.05741044]] [[-12.53518463]]
[[-119.25644799  155.91802658   64.84881002]] [[117.29939957]]
[[ 197.83628653 -114.08044621  166.80107735]] [[347.82916394]]
[[588.85759504  20.66125653 223.0680123 ]] [[445.68897542]]
[[447.49727241 229.75008397 141.97813872]] [[390.8590797]]
[[ 395.75872997 -731.3686965  -531.40578616]] [[-957.38793846]]
[[ -402.00559549   141.12033505 -1303.48847529]] [[-571.28253639]]
[[-1084.9706482    -45.12933828 -1010.97342542]] [[-635.40941619]]
[[-573.01243088 -493.45243252  719.79468091]] [[-348.73589778]]
[[-165.00943276  295.88506534  286.11014594]] [[-46.55817632]]
[[-14.84503602 -29.05208911   4.67011668]] [[-9.65309909]]
[[-38.71735309 -10.13653923  -4.58002482]] [[-8.72451028]]
[[-75.54598944  61.36896045 -52.98149618]] [[-22.15600083]]
[[ -37.5521713   111.56678151 -139.36625537]] [[-102.90260457]]
[[ 151.05727183  -81.71966198 -121.36027052]] [[-256.06151459

[[-275.86829968  -39.18356712  116.33728205]] [[58.27825273]]
[[310.90274612 123.03115601   8.27199862]] [[118.48847867]]
[[222.4159693  168.60207585 -57.49612883]] [[-79.67849283]]
[[ 17.1679843  213.31751233 123.18401821]] [[-397.3713363]]
[[-447.10243892 -105.45154495  247.97777241]] [[-160.5732594]]
[[-84.18856357  70.51439071 293.65466312]] [[421.07003568]]
[[ 864.65844118 -601.86871876 -390.19796415]] [[-370.76734918]]
[[ -695.22422218 -1151.71163887  -101.6878095 ]] [[-111.02295]]
[[ 358.28056919  -32.66637543 -576.08653827]] [[402.82681268]]
[[930.35489214 995.53028353  72.48050149]] [[-259.34413122]]
[[-1240.02860827   462.60636193   564.19154661]] [[-629.31235017]]
[[-424.29099289  553.01012376  760.84632349]] [[-16.50658858]]
[[957.90860625 826.08341682 473.97814009]] [[74.5369914]]
[[30.40947522 -6.76359383 -7.70219586]] [[6.31499549]]
[[ 21.35273142   4.4359612  -41.13658055]] [[10.14825791]]
[[   5.31474242   48.32920516 -141.46686637]] [[13.01395966]]
[[ -16.06899675   8

[[-145.25240405  -65.24692855  -97.02997002]] [[-82.94696443]]
[[-175.68860075  -88.91906594  -39.52771362]] [[-89.07851735]]
[[-317.66593762 -120.99380368  -73.13600556]] [[95.05144136]]
[[  51.87534938 -194.07261229 -145.4965468 ]] [[-15.59332991]]
[[-146.32040937   28.13465381 -242.19669842]] [[-207.32052246]]
[[-204.40238721 -137.71205768 -197.08009048]] [[-318.93598426]]
[[-378.79045779  -99.60333124   97.50499397]] [[134.54169533]]
[[-195.30392907 -445.22823991 -249.58547766]] [[323.24292558]]
[[936.57550369  52.5401723    5.36444994]] [[-147.68005284]]
[[184.9029981  205.68231957  36.40160667]] [[-228.64679934]]
[[829.03766469 193.6241608    2.44320116]] [[-337.14383927]]
[[ 159.23746898   85.49417448 -273.24657677]] [[-479.32708851]]
[[-1078.96897113     4.61229006  -168.31245725]] [[-25.17352498]]
[[ -881.60395427 -1136.27517009   405.99612493]] [[589.44622645]]
[[-817.5955188  -719.68429136  -92.60989116]] [[60.76626243]]
[[  3.49963192 -15.5808326   -6.92615693]] [[-7.399008

[[  4.89077149 -15.08018093 -43.0731911 ]] [[-32.37837978]]
[[ -36.07254452   -6.52772469 -146.93095875]] [[-92.80709448]]
[[ -53.47757048   54.60298835 -241.78558491]] [[-110.62399607]]
[[ 73.2577856  135.3513992  -11.59410608]] [[71.27987238]]
[[ -37.45290423 -101.50970974   54.28003633]] [[-223.00718272]]
[[  96.76373835  -74.03148393 -161.60575694]] [[4.09404414]]
[[-305.76637047 -168.61369772 -577.00332423]] [[-399.99759751]]
[[  22.82393996   92.09668093 -334.20041291]] [[251.4933567]]
[[ 240.78078459 -103.38466522  342.30340536]] [[-298.1321876]]
[[  40.49718005 -397.7290739   120.96577498]] [[82.73457654]]
[[ 455.03941402 -253.68666448  272.12889548]] [[287.11084651]]
[[-559.93076868 -638.36022416  138.95448688]] [[-153.33481382]]
[[ 494.69491689 -242.34376966 -514.01003987]] [[-418.1903658]]
[[ -368.57794598   381.96599289 -1047.67218943]] [[-35.21289368]]
[[-641.68619265  339.50603471 -380.35055099]] [[-342.52052433]]
[[305.23749518 720.84609851 298.41069132]] [[-402.23980772

[[ 136.94804733 -276.87942278  247.81662327]] [[-639.04979532]]
[[-909.99888473  746.60903119 -763.77783927]] [[1619.019655]]
[[ 24.99993578 -22.46476108  -7.28195642]] [[2.51748686]]
[[ 19.63869053 -20.92795506  12.07733423]] [[1.82545475]]
[[17.08771925  6.747638   43.34497367]] [[-2.05708559]]
[[ 14.31165034  57.84089586 -11.5351224 ]] [[-35.6566388]]
[[ -15.59460368   13.97228128 -255.08310575]] [[-94.47146062]]
[[-151.25912695 -210.00464797  -44.27910761]] [[-110.41942378]]
[[246.82370617  94.05856215  20.39001433]] [[38.72163946]]
[[254.48472243 336.20814518  90.6711578 ]] [[-219.97074038]]
[[  -7.27090656  194.4162602  -265.73307973]] [[44.47569044]]
[[-196.57620663 -245.76187932 -292.40237935]] [[-223.36271307]]
[[ -57.88871291 -457.29601337    3.56816653]] [[217.94828124]]
[[1021.07684592  311.42664161 -482.22456334]] [[-149.62333526]]
[[-340.04607272 -116.36476137  188.13149964]] [[-25.68982978]]
[[ 586.48845557   51.5617335  1111.50620139]] [[662.0718631]]
[[180.22764749 776

[[  715.17804611  -338.41065615 -1099.35375   ]] [[-176.06963332]]
[[-1314.3312481   -689.48551322  -469.26862362]] [[-1160.58422853]]
[[-396.63787682 -429.11732652  -35.51822079]] [[-1217.57695772]]
[[735.49499149 737.16391445 722.80961675]] [[-219.90543768]]
[[23.85820744 -1.22010033  7.6033484 ]] [[2.32365846]]
[[  7.85510069 -24.34676864  28.89442043]] [[-6.42817518]]
[[  1.47388257 -57.81432038  46.37948671]] [[-55.92853941]]
[[ 23.28589543 -22.56326652 -35.09437025]] [[-165.83215841]]
[[   7.90998071  133.44554275 -216.29470822]] [[-187.78087548]]
[[-459.62712923 -276.33000651  291.9365677 ]] [[-27.18931061]]
[[280.7683917  -31.49955869 115.73275761]] [[67.49767863]]
[[ 221.50369925  -58.26124967 -105.56976767]] [[-321.01629436]]
[[  23.11692507  177.1038515  -474.4821743 ]] [[-265.00760168]]
[[-685.12137772 -283.6031256   137.61063311]] [[-438.9806628]]
[[-320.35387268 -379.30360992  570.2205803 ]] [[480.77525413]]
[[1004.48106938  453.6410512  -519.32348826]] [[-56.6380851]]
[[

[[-34.19505095 147.31656918 395.80407413]] [[-48.9261316]]
[[ 17.22641281  96.80742191 268.41177913]] [[1408.39075965]]
[[ 540.45583266 -322.65101285 -545.90279244]] [[159.42748592]]
[[-1650.85559163  -884.13481966  -226.16369616]] [[428.47756604]]
[[-1269.39064844  -962.19940701   513.42691201]] [[-877.30530971]]
[[1687.42830327  432.03148723 -257.48408863]] [[-713.50717291]]
[[  1.05600583 -30.28663068  16.84829944]] [[-4.91382727]]
[[-15.23401058 -37.89360266 -12.75348437]] [[-33.62189428]]
[[ -30.32166436  -52.48742491 -120.44851893]] [[-120.46478218]]
[[  -6.43398131  -58.38080839 -233.408899  ]] [[-188.96360006]]
[[ 56.89718134 -17.98753179 -12.79782423]] [[19.08256467]]
[[-270.49853916  -70.34460858  115.22727674]] [[-13.09678158]]
[[222.02589354 157.27255216 -75.93532722]] [[8.43774646]]
[[  57.00118651   85.61057783 -636.66783813]] [[-381.75663598]]
[[  41.39533841   65.55830374 -286.51308629]] [[-63.42363085]]
[[-203.31176199  -87.90925155  376.10482168]] [[249.22381629]]
[[-

[[  2.35405702  70.83437849 535.94680041]] [[317.62199254]]
[[ 273.13784752 -298.36371679 -651.93462871]] [[792.70332711]]
[[-467.5134315  -171.71109129  605.21049065]] [[227.89586743]]
[[633.92676064 322.63268717 948.98942004]] [[-149.72249406]]
[[ 1239.1671795  -1031.59131702 -2092.40223617]] [[-190.07727986]]
[[-489.33162809 -735.16376403 -384.95192925]] [[-1647.36985929]]
[[-882.80907059  194.10711442 1056.87141214]] [[-1151.0143787]]
[[ 299.64486334  543.3148774  -119.58734873]] [[72.31735817]]
[[ 27.01768843 -10.93719193 -21.12496041]] [[4.82836527]]
[[41.42604937 -6.45318656 15.42717257]] [[-12.11235476]]
[[79.00551414  3.57662514 86.17619654]] [[-75.49370146]]
[[ 56.6438949  -29.85436807  32.7507199 ]] [[-167.49483029]]
[[-164.58495832 -153.09483944 -316.64054427]] [[-115.35218376]]
[[-117.34188246 -117.34409674  145.63383257]] [[-77.9592903]]
[[271.29531904 220.06380644 245.60726521]] [[43.72093082]]
[[350.34948773  98.87445627  67.95708089]] [[-161.39169741]]
[[-132.83591024 

[[54.73233203  2.43934382  2.32006644]] [[-14.27294422]]
[[ 69.50910923  26.89687724 -54.35628121]] [[-3.04568996]]
[[-67.88805253  33.97631072 -73.39267516]] [[45.79096045]]
[[-40.03648854 -60.54292774 243.56784928]] [[-47.5886196]]
[[ 517.75117245  158.23870265 -178.98218974]] [[86.46564197]]
[[405.42786067 132.26790859 -67.50755586]] [[-90.40536577]]
[[-157.71069864   43.57260981 -384.2648176 ]] [[-34.88379359]]
[[  90.40949162 -131.26639805  384.99338871]] [[65.27048967]]
[[267.4677477   35.41162413 -55.24860082]] [[217.83869102]]
[[ 710.34263746  261.0061503  -298.76007635]] [[232.25565466]]
[[-547.5962135  -299.47807105  253.49444214]] [[-449.56560631]]
[[ 906.64885567  -61.64034124 -182.60106544]] [[-363.09619001]]
[[  869.59567034   232.0878259  -1050.83880923]] [[408.627139]]
[[-2333.23356071  -748.18957537   666.74520185]] [[-215.12551401]]
[[ -76.56654815 -232.26995845  266.51478958]] [[363.83429973]]
[[1412.18250711  531.24263525 -450.1781942 ]] [[292.78633527]]
[[ -1.18403

[[  833.31380048  -220.82261789 -1068.11541825]] [[723.05496287]]
[[-1255.49580486 -2477.06732791   234.94680061]] [[-660.00092119]]
[[ -830.23492832 -1434.67603418   972.42093873]] [[-1169.26900688]]
[[454.21128279 -50.11063955 486.22961782]] [[-1080.05092866]]
[[ 14.44426847 -14.0496397  -19.85538656]] [[4.27839058]]
[[ 11.7830455  -21.62697557 -30.43988553]] [[-24.8870551]]
[[ 25.26213284 -60.66313887 -82.9133303 ]] [[-97.71043999]]
[[  38.97279541 -134.95021669 -149.75805076]] [[-140.89753107]]
[[ -46.57244459 -116.77549651  -44.93921642]] [[38.86433704]]
[[-313.8688289    41.16910973  144.16332789]] [[-191.81660561]]
[[117.42507415  99.81316344 -91.54201947]] [[-67.15519394]]
[[ 150.71368992 -237.24138537 -363.26743587]] [[-478.35778532]]
[[ -23.12834515 -294.0772926  -215.46530331]] [[91.88761954]]
[[-227.49633502  -15.64506968   76.00045375]] [[-249.40641356]]
[[-298.95572364  273.50425968  346.84388026]] [[39.55760203]]
[[ 637.3801959    89.47727282 -235.74466957]] [[250.374614

[[-294.42143529 -300.19298458 1048.62333796]] [[-1209.62385333]]
[[654.97127099  66.57219937 -26.08346111]] [[-1384.90248571]]
time taken to train: 6.122346639633179 seconds
[[ 12.92661144 -10.76991648  -0.66765682]] [[-14.46368465]]
[[ 13.65964828 -15.86315789  -2.28480891]] [[-23.0427918]]
[[ 31.40817511 -20.48176399 -28.75858942]] [[-60.77448367]]
[[ 45.80673563 -16.57177965 -85.50678312]] [[-130.5177019]]
[[-28.44832654  -3.44604335 -71.46347546]] [[-132.27391795]]
[[-171.66395401 -110.61798632  126.95077   ]] [[-88.16374858]]
[[216.90386094  58.41861219 -60.9262617 ]] [[-29.90394414]]
[[ 196.3670552   -49.9311597  -249.41730191]] [[-231.32732614]]
[[ -61.50794767   19.97325018 -201.43638062]] [[-177.52700583]]
[[-198.19725924 -160.3591108   207.01263853]] [[-195.4295429]]
[[-72.88609386 -66.22567155 186.44843625]] [[171.92065568]]
[[ 554.07928469  -22.78719257 -264.26693972]] [[11.71322299]]
[[-547.5396838  -242.40678375  227.26008765]] [[223.18148587]]
[[558.97155755 143.22230094

0.018200080000024172

In [ ]:
# this is my parameter
model = Model(30, 500, 3)
agent = Agent(15, 0.1, 0.03, model, 10000, 5, 5, 1, 30)
agent.fit(500, 100)
agent.buy()

In [ ]:
# this is from bayesian
model = Model(20, 176, 3)
agent = Agent(
    34, 0.7152490670931403, 0.28208006704411104, model, 10000, 5, 5, 1, 20
)
agent.fit(500, 100)
agent.buy()